/* <LICENSE>
* 
* Copyright (C) 2022 Louis F. Roehrs, All rights reserved.
* 
* </LICENSE>
*  */




import * as ALL_OPERATORS from './operators';

const {
  ANNIVERSARY_OPERATORS,
  BEFORE_AFTER_DATE_OPERATORS,
  BLANK_OPERATORS,
  CONTAIN_ONE_OF_OPERATORS,
  CONTAIN_OPERATORS,
  DATA_AGGREGATION_OPERATORS,
  ENDS_WITH_ONE_OF_OPERATORS,
  ENDS_WITH_OPERATORS,
  EXACT_OPERATORS,
  GREATER_THAN_OPERATORS,
  HAS_OPERATORS,
  IS_ONE_OF_OPERATORS,
  IS_OPERATORS,
  LESS_THAN_OPERATORS,
  PERIOD_EQUAL_OPERATORS,
  RANGE_OPERATORS,
  STARTS_WITH_ONE_OF_OPERATORS,
  STARTS_WITH_OPERATORS,
  TODAY_OPERATORS,
  WITHIN_RANGE_OPERATORS,
  WITHIN_OPERATORS,
} = ALL_OPERATORS;

export const ALL_AVAILABLE_OPERATORS = Object.values(ALL_OPERATORS).flat();

export const CUSTOM_RULE_DEFAULT_OPERATORS = HAS_OPERATORS;

export const DATE_RULE_OPERATORS = [
  ...TODAY_OPERATORS,
  ...BEFORE_AFTER_DATE_OPERATORS,
  ...IS_OPERATORS,
  ...IS_ONE_OF_OPERATORS,
  ...PERIOD_EQUAL_OPERATORS,
  ...ANNIVERSARY_OPERATORS,
  ...WITHIN_OPERATORS,
  ...EXACT_OPERATORS,
  ...RANGE_OPERATORS,
  ...WITHIN_RANGE_OPERATORS,
  ...BLANK_OPERATORS,
];

export const NUMBER_RULE_OPERATORS = [
  ...IS_OPERATORS,
  ...IS_ONE_OF_OPERATORS,
  ...LESS_THAN_OPERATORS,
  ...GREATER_THAN_OPERATORS,
  ...RANGE_OPERATORS,
  ...BLANK_OPERATORS,
];

export const STRING_RULE_OPERATORS = [
  ...IS_OPERATORS,
  ...IS_ONE_OF_OPERATORS,
  ...BLANK_OPERATORS,
  ...CONTAIN_OPERATORS,
  ...CONTAIN_ONE_OF_OPERATORS,
  ...STARTS_WITH_OPERATORS,
  ...STARTS_WITH_ONE_OF_OPERATORS,
  ...ENDS_WITH_OPERATORS,
  ...ENDS_WITH_ONE_OF_OPERATORS,
];

export const SELECT_RULE_OPERATORS = [...STRING_RULE_OPERATORS,...DATA_AGGREGATION_OPERATORS];
