/* <LICENSE>
* 
* Copyright (C) 2022 Louis F. Roehrs, All rights reserved.
* 
* </LICENSE>
*  */



const myRowDependantMenusOld = {
  "rowDependentDropdown" : {
    "itemsByRow" : {
      "23598" :{ items: [
          { label:"hi23598", value:"hi23598"},
          { label:"hello23598", value:"hello23598"}
        ]},
        "6072":{ items: [
            { label:"hi6072", value:"hi6072"},
            { label:"hello6072", value:"hello6072"}
          ]}
      }
    }
  }

const mydata = {
  "rows": [
    {
      "upc": "00001780001278",
      "progress": 1,
      "opportunity":.95,
      "comboDropdownTest":"George",
      "rowDependentDropdown" :"hi23598",
      "locationName": "CRYSTAL CITY",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": false,
      "productName": "PURINA ONE URINARY 16LB",
      "size": "16",
      "uom": "LB",
      "zone": "ZONE 130",
      "currentPrice": "$0.00",
      "currentSales": "$0",
      "currentGM": "$0",
      "currentGMPct": "0.0%",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CATFOOD",
      "currentVolume": "0",
      "sizeClass": "X-SMALL",
      "sizeFamily": "SPCL CARE URINARY",
      "brand": "PURINA_SPCLCARE",
      "brandClass": "NATIONAL BRAND",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "strategyRunId": "55",
      "lineGroup": "00001780001278",
      "customerLocationKey": "000117",
      "countBrokenRules": "0",
      "isPrePriced": 0,
      "cost": "$12.84",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "23598",
      "priceEffectiveDate":"May 20, 2021",
      "dropdownTest":2,
      "numbersRoundedTo2Decimals" : 12.4234234234,
      "numbersCurrencyRoundedTo2Decimals" : 12.4234234234,
    },
    {
      "upc": "00003470058410",
      "progress": .99,
      "opportunity":.94,
      "comboDropdownTest":"FRED",
      "rowDependentDropdown" :"",
      "priceEffectiveDate":"5/20/2021",
      "locationName": "SINTON",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": true,
      "productName": "ALLEN S PURPLE HULL PEAS",
      "size": "16",
      "uom": "OZ",
      "zone": "ZONE 131",
      "currentPrice": "$0.45",
      "lastApprovedPrice": "$2.30",
      "currentSales": "$26",
      "currentGM": "$3",
      "currentGMPct": "12.6%",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CANNEDDRYSOAKBEANS",
      "currentVolume": "57",
      "brand": "ALLENS",
      "brandClass": "NATIONAL",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "lastApprovedPricePerUOM": "$0.15",
      "strategyRunId": "55",
      "lineGroup": "00003470058410",
      "customerLocationKey": "000115",
      "countBrokenRules": "0",
      "lastApprovedDate": "Nov 30, 2020 8:47:24 PM",
      "isPrePriced": 0,
      "attribute0": "GROCERY",
      "attribute1": "N",
      "attribute2": "CANNED DRY SOAK BEANS",
      "cost": "$0.39",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "6072",
      "numbersRoundedTo2Decimals" : 2.45344,
      "numbersCurrencyRoundedTo2Decimals" : 2.45344,
    },
    {
      "disabled":true,
      "upc": "00003470058410",
      "progress": .98,
      "opportunity":.93,
      "comboDropdownTest":"ETHEL",
      "rowDependentDropdown" :"hello6074",
      "locationName": "CC12 WEBER/HOLLY",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": true,
      "productName": "ALLEN S PURPLE HULL PEAS",
      "size": "16",
      "uom": "OZ",
      "zone": "ZONE 131",
      "currentPrice": "$0.45",
      "lastApprovedPrice": "$2.30",
      "currentSales": "$50",
      "currentGM": "$6",
      "currentGMPct": "12.6%",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CANNEDDRYSOAKBEANS",
      "currentVolume": "110",
      "brand": "ALLENS",
      "brandClass": "NATIONAL",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "lastApprovedPricePerUOM": "$0.15",
      "strategyRunId": "55",
      "lineGroup": "00003470058410",
      "customerLocationKey": "000139",
      "countBrokenRules": "0",
      "lastApprovedDate": "Nov 30, 2020 8:47:24 PM",
      "isPrePriced": 0,
      "attribute0": "GROCERY",
      "attribute1": "N",
      "attribute2": "CANNED DRY SOAK BEANS",
      "cost": "$0.39",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "6074",
      "numbersRoundedTo2Decimals" : 5.42344,
      "numbersCurrencyRoundedTo2Decimals" : 5.42344,
    },
    {
      "upc": "00003470058410",
      "locationName": "KENEDY",
      "progress": .97,
      "opportunity":.90,
      "comboDropdownTest":"Merideth",
      "rowDependentDropdown" :"hi6076",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": true,
      "productName": "ALLEN S PURPLE HULL PEAS",
      "size": "16",
      "uom": "OZ",
      "zone": "ZONE 131",
      "currentPrice": "$0.45",
      "lastApprovedPrice": "$2.30",
      "currentSales": "$42",
      "currentGM": "$5",
      "currentGMPct": "12.6%",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CANNEDDRYSOAKBEANS",
      "currentVolume": "93",
      "brand": "ALLENS",
      "brandClass": "NATIONAL",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "lastApprovedPricePerUOM": "$0.15",
      "strategyRunId": "55",
      "lineGroup": "00003470058410",
      "customerLocationKey": "000155",
      "countBrokenRules": "0",
      "lastApprovedDate": "Nov 30, 2020 8:47:24 PM",
      "isPrePriced": 0,
      "attribute0": "GROCERY",
      "attribute1": "N",
      "attribute2": "CANNED DRY SOAK BEANS",
      "cost": "$0.39",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "6076",
      "numbersRoundedTo2Decimals" : 15.42344,
      "numbersCurrencyRoundedTo2Decimals" : 15.42344,
    },
    {
      "upc": "00003470058410",
      "locationName": "MATHIS",
      "progress": .89,
      "opportunity":.89,
      "comboDropdownTest":"ViCtoria",
      "rowDependentDropdown" :"hello6078",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": true,
      "productName": "ALLEN S PURPLE HULL PEAS",
      "size": "16",
      "uom": "OZ",
      "zone": "ZONE 131",
      "currentPrice": "$0.45",
      "lastApprovedPrice": "$2.30",
      "currentSales": "$39",
      "currentGM": "$5",
      "currentGMPct": "12.6%",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CANNEDDRYSOAKBEANS",
      "currentVolume": "86",
      "brand": "ALLENS",
      "brandClass": "NATIONAL",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "lastApprovedPricePerUOM": "$0.15",
      "strategyRunId": "55",
      "lineGroup": "00003470058410",
      "customerLocationKey": "000160",
      "countBrokenRules": "0",
      "lastApprovedDate": "Nov 30, 2020 8:47:24 PM",
      "isPrePriced": 0,
      "attribute0": "GROCERY",
      "attribute1": "N",
      "attribute2": "CANNED DRY SOAK BEANS",
      "cost": "$0.39",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "6078",
      "numbersRoundedTo2Decimals" : 0.4,
      "numbersCurrencyRoundedTo2Decimals" : 0.4
    },
    {
      "upc": "00003470058410",
      "locationName": "FALFURRIAS",
      "progress": .7,
      "opportunity":.70,
      "comboDropdownTest":"Elizabeth",
      "rowDependentDropdown" :"hello6079",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": true,
      "productName": "ALLEN S PURPLE HULL PEAS",
      "size": "16",
      "uom": "OZ",
      "zone": "ZONE 131",
      "currentPrice": "$0.45",
      "lastApprovedPrice": "$2.30",
      "currentSales": "$37",
      "currentGM": "$5",
      "currentGMPct": "12.6%",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CANNEDDRYSOAKBEANS",
      "currentVolume": "83",
      "brand": "ALLENS",
      "brandClass": "NATIONAL",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "lastApprovedPricePerUOM": "$0.15",
      "strategyRunId": "55",
      "lineGroup": "00003470058410",
      "customerLocationKey": "000200",
      "countBrokenRules": "0",
      "lastApprovedDate": "Nov 30, 2020 8:47:24 PM",
      "isPrePriced": 0,
      "attribute0": "GROCERY",
      "attribute1": "N",
      "attribute2": "CANNED DRY SOAK BEANS",
      "cost": "$0.39",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "6079",
      "numbersRoundedTo2Decimals" : 0.494,
      "numbersCurrencyRoundedTo2Decimals" : 0.494
    },
    {
      "upc": "00003470058410",
      "locationName": "CC18 SPID/WALDRON",
      "progress": .69,
      "opportunity":.65,
      "comboDropdownTest":"Graham",
      "rowDependentDropdown" :"hi6080",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": true,
      "productName": "ALLEN S PURPLE HULL PEAS",
      "size": "16",
      "uom": "OZ",
      "zone": "ZONE 131",
      "currentPrice": "$0.45",
      "lastApprovedPrice": "$2.30",
      "currentSales": "$103",
      "currentGM": "($13)",
      "currentGMPct": "(12.6%)",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CANNEDDRYSOAKBEANS",
      "currentVolume": "230",
      "brand": "ALLENS",
      "brandClass": "NATIONAL",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "lastApprovedPricePerUOM": "$0.15",
      "strategyRunId": "55",
      "lineGroup": "00003470058410",
      "customerLocationKey": "000204",
      "countBrokenRules": "0",
      "lastApprovedDate": "Nov 30, 2020 8:47:24 PM",
      "isPrePriced": 0,
      "attribute0": "GROCERY",
      "attribute1": "N",
      "attribute2": "CANNED DRY SOAK BEANS",
      "cost": "$0.39",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "6080",
      "numbersRoundedTo2Decimals" : 0.495,
      "numbersCurrencyRoundedTo2Decimals" : 0.495

    },
    {
      "upc": "00003470058410",
      "locationName": "CC06 ALAMEDA/ROBERTS",
      "progress": .68,
      "opportunity":.68,
      "comboDropdownTest":"Sylvia",
      "rowDependentDropdown" :"hi6081",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": true,
      "productName": "ALLEN S PURPLE HULL PEAS",
      "size": "16",
      "uom": "OZ",
      "zone": "ZONE 131",
      "currentPrice": "$0.45",
      "lastApprovedPrice": "$2.30",
      "currentSales": "$63",
      "currentGM": "$8",
      "currentGMPct": "12.6%",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CANNEDDRYSOAKBEANS",
      "currentVolume": "139",
      "brand": "ALLENS",
      "brandClass": "NATIONAL",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "lastApprovedPricePerUOM": "$0.15",
      "strategyRunId": "55",
      "lineGroup": "00003470058410",
      "customerLocationKey": "000210",
      "countBrokenRules": "0",
      "lastApprovedDate": "Nov 30, 2020 8:47:24 PM",
      "isPrePriced": 0,
      "attribute0": "GROCERY",
      "attribute1": "N",
      "attribute2": "CANNED DRY SOAK BEANS",
      "cost": "$0.39",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "6081",
      "numbersRoundedTo2Decimals" : 0.496,
      "numbersCurrencyRoundedTo2Decimals" : 0.496
    }
  ],
  "total": 8
}

const infiniteScrollData = {
  "rows": [
    {
      "upc": "00001780001278",
      "progress": 1,
      "opportunity":.95,
      "comboDropdownTest":"George",
      "rowDependentDropdown" :"hi23598",
      "locationName": "CRYSTAL CITY",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": false,
      "productName": "PURINA ONE URINARY 16LB",
      "size": "16",
      "uom": "LB",
      "zone": "ZONE 130",
      "currentPrice": "$0.00",
      "currentSales": "$0",
      "currentGM": "$0",
      "currentGMPct": "0.0%",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CATFOOD",
      "currentVolume": "0",
      "sizeClass": "X-SMALL",
      "sizeFamily": "SPCL CARE URINARY",
      "brand": "PURINA_SPCLCARE",
      "brandClass": "NATIONAL BRAND",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "strategyRunId": "55",
      "lineGroup": "00001780001278",
      "customerLocationKey": "000117",
      "countBrokenRules": "0",
      "isPrePriced": 0,
      "cost": "$12.84",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "23598",
      "priceEffectiveDate":"May 20, 2021",
      "dropdownTest":2,
      "numbersRoundedTo2Decimals" : 12.4234234234,
      "numbersCurrencyRoundedTo2Decimals" : 12.4234234234,
    },
    {
      "upc": "00003470058410",
      "progress": .99,
      "opportunity":.94,
      "comboDropdownTest":"FRED",
      "rowDependentDropdown" :"",
      "priceEffectiveDate":"5/20/2021",
      "locationName": "SINTON",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": true,
      "productName": "ALLEN S PURPLE HULL PEAS",
      "size": "16",
      "uom": "OZ",
      "zone": "ZONE 131",
      "currentPrice": "$0.45",
      "lastApprovedPrice": "$2.30",
      "currentSales": "$26",
      "currentGM": "$3",
      "currentGMPct": "12.6%",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CANNEDDRYSOAKBEANS",
      "currentVolume": "57",
      "brand": "ALLENS",
      "brandClass": "NATIONAL",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "lastApprovedPricePerUOM": "$0.15",
      "strategyRunId": "55",
      "lineGroup": "00003470058410",
      "customerLocationKey": "000115",
      "countBrokenRules": "0",
      "lastApprovedDate": "Nov 30, 2020 8:47:24 PM",
      "isPrePriced": 0,
      "attribute0": "GROCERY",
      "attribute1": "N",
      "attribute2": "CANNED DRY SOAK BEANS",
      "cost": "$0.39",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "6072",
      "numbersRoundedTo2Decimals" : 2.45344,
      "numbersCurrencyRoundedTo2Decimals" : 2.45344,
    },
    {
      "disabled":true,
      "upc": "00003470058410",
      "progress": .98,
      "opportunity":.93,
      "comboDropdownTest":"ETHEL",
      "rowDependentDropdown" :"hello6074",
      "locationName": "CC12 WEBER/HOLLY",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": true,
      "productName": "ALLEN S PURPLE HULL PEAS",
      "size": "16",
      "uom": "OZ",
      "zone": "ZONE 131",
      "currentPrice": "$0.45",
      "lastApprovedPrice": "$2.30",
      "currentSales": "$50",
      "currentGM": "$6",
      "currentGMPct": "12.6%",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CANNEDDRYSOAKBEANS",
      "currentVolume": "110",
      "brand": "ALLENS",
      "brandClass": "NATIONAL",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "lastApprovedPricePerUOM": "$0.15",
      "strategyRunId": "55",
      "lineGroup": "00003470058410",
      "customerLocationKey": "000139",
      "countBrokenRules": "0",
      "lastApprovedDate": "Nov 30, 2020 8:47:24 PM",
      "isPrePriced": 0,
      "attribute0": "GROCERY",
      "attribute1": "N",
      "attribute2": "CANNED DRY SOAK BEANS",
      "cost": "$0.39",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "6074",
      "numbersRoundedTo2Decimals" : 5.42344,
      "numbersCurrencyRoundedTo2Decimals" : 5.42344,
    },
    {
      "upc": "00003470058410",
      "locationName": "KENEDY",
      "progress": .97,
      "opportunity":.90,
      "comboDropdownTest":"Merideth",
      "rowDependentDropdown" :"hi6076",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": true,
      "productName": "ALLEN S PURPLE HULL PEAS",
      "size": "16",
      "uom": "OZ",
      "zone": "ZONE 131",
      "currentPrice": "$0.45",
      "lastApprovedPrice": "$2.30",
      "currentSales": "$42",
      "currentGM": "$5",
      "currentGMPct": "12.6%",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CANNEDDRYSOAKBEANS",
      "currentVolume": "93",
      "brand": "ALLENS",
      "brandClass": "NATIONAL",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "lastApprovedPricePerUOM": "$0.15",
      "strategyRunId": "55",
      "lineGroup": "00003470058410",
      "customerLocationKey": "000155",
      "countBrokenRules": "0",
      "lastApprovedDate": "Nov 30, 2020 8:47:24 PM",
      "isPrePriced": 0,
      "attribute0": "GROCERY",
      "attribute1": "N",
      "attribute2": "CANNED DRY SOAK BEANS",
      "cost": "$0.39",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "6076",
      "numbersRoundedTo2Decimals" : 15.42344,
      "numbersCurrencyRoundedTo2Decimals" : 15.42344,
    },
    {
      "upc": "00003470058410",
      "locationName": "MATHIS",
      "progress": .89,
      "opportunity":.89,
      "comboDropdownTest":"ViCtoria",
      "rowDependentDropdown" :"hello6078",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": true,
      "productName": "ALLEN S PURPLE HULL PEAS",
      "size": "16",
      "uom": "OZ",
      "zone": "ZONE 131",
      "currentPrice": "$0.45",
      "lastApprovedPrice": "$2.30",
      "currentSales": "$39",
      "currentGM": "$5",
      "currentGMPct": "12.6%",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CANNEDDRYSOAKBEANS",
      "currentVolume": "86",
      "brand": "ALLENS",
      "brandClass": "NATIONAL",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "lastApprovedPricePerUOM": "$0.15",
      "strategyRunId": "55",
      "lineGroup": "00003470058410",
      "customerLocationKey": "000160",
      "countBrokenRules": "0",
      "lastApprovedDate": "Nov 30, 2020 8:47:24 PM",
      "isPrePriced": 0,
      "attribute0": "GROCERY",
      "attribute1": "N",
      "attribute2": "CANNED DRY SOAK BEANS",
      "cost": "$0.39",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "6078",
      "numbersRoundedTo2Decimals" : 0.4,
      "numbersCurrencyRoundedTo2Decimals" : 0.4
    },
    {
      "upc": "00003470058410",
      "locationName": "FALFURRIAS",
      "progress": .7,
      "opportunity":.70,
      "comboDropdownTest":"Elizabeth",
      "rowDependentDropdown" :"hello6079",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": true,
      "productName": "ALLEN S PURPLE HULL PEAS",
      "size": "16",
      "uom": "OZ",
      "zone": "ZONE 131",
      "currentPrice": "$0.45",
      "lastApprovedPrice": "$2.30",
      "currentSales": "$37",
      "currentGM": "$5",
      "currentGMPct": "12.6%",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CANNEDDRYSOAKBEANS",
      "currentVolume": "83",
      "brand": "ALLENS",
      "brandClass": "NATIONAL",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "lastApprovedPricePerUOM": "$0.15",
      "strategyRunId": "55",
      "lineGroup": "00003470058410",
      "customerLocationKey": "000200",
      "countBrokenRules": "0",
      "lastApprovedDate": "Nov 30, 2020 8:47:24 PM",
      "isPrePriced": 0,
      "attribute0": "GROCERY",
      "attribute1": "N",
      "attribute2": "CANNED DRY SOAK BEANS",
      "cost": "$0.39",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "6079",
      "numbersRoundedTo2Decimals" : 0.494,
      "numbersCurrencyRoundedTo2Decimals" : 0.494
    },
    {
      "upc": "00003470058410",
      "locationName": "CC18 SPID/WALDRON",
      "progress": .69,
      "opportunity":.65,
      "comboDropdownTest":"Graham",
      "rowDependentDropdown" :"hi6080",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": true,
      "productName": "ALLEN S PURPLE HULL PEAS",
      "size": "16",
      "uom": "OZ",
      "zone": "ZONE 131",
      "currentPrice": "$0.45",
      "lastApprovedPrice": "$2.30",
      "currentSales": "$103",
      "currentGM": "($13)",
      "currentGMPct": "(12.6%)",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CANNEDDRYSOAKBEANS",
      "currentVolume": "230",
      "brand": "ALLENS",
      "brandClass": "NATIONAL",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "lastApprovedPricePerUOM": "$0.15",
      "strategyRunId": "55",
      "lineGroup": "00003470058410",
      "customerLocationKey": "000204",
      "countBrokenRules": "0",
      "lastApprovedDate": "Nov 30, 2020 8:47:24 PM",
      "isPrePriced": 0,
      "attribute0": "GROCERY",
      "attribute1": "N",
      "attribute2": "CANNED DRY SOAK BEANS",
      "cost": "$0.39",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "6080",
      "numbersRoundedTo2Decimals" : 0.495,
      "numbersCurrencyRoundedTo2Decimals" : 0.495

    },
    {
      "upc": "00003470058410",
      "locationName": "CC06 ALAMEDA/ROBERTS",
      "progress": .68,
      "opportunity":.68,
      "comboDropdownTest":"Sylvia",
      "rowDependentDropdown" :"hi6081",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": true,
      "productName": "ALLEN S PURPLE HULL PEAS",
      "size": "16",
      "uom": "OZ",
      "zone": "ZONE 131",
      "currentPrice": "$0.45",
      "lastApprovedPrice": "$2.30",
      "currentSales": "$63",
      "currentGM": "$8",
      "currentGMPct": "12.6%",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CANNEDDRYSOAKBEANS",
      "currentVolume": "139",
      "brand": "ALLENS",
      "brandClass": "NATIONAL",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "lastApprovedPricePerUOM": "$0.15",
      "strategyRunId": "55",
      "lineGroup": "00003470058410",
      "customerLocationKey": "000210",
      "countBrokenRules": "0",
      "lastApprovedDate": "Nov 30, 2020 8:47:24 PM",
      "isPrePriced": 0,
      "attribute0": "GROCERY",
      "attribute1": "N",
      "attribute2": "CANNED DRY SOAK BEANS",
      "cost": "$0.39",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "6081",
      "numbersRoundedTo2Decimals" : 0.496,
      "numbersCurrencyRoundedTo2Decimals" : 0.496
    },
    {
      "upc": "00001780001278",
      "progress": 1,
      "opportunity":.95,
      "comboDropdownTest":"George",
      "rowDependentDropdown" :"hi23598",
      "locationName": "CRYSTAL CITY",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": false,
      "productName": "PURINA ONE URINARY 16LB",
      "size": "16",
      "uom": "LB",
      "zone": "ZONE 130",
      "currentPrice": "$0.00",
      "currentSales": "$0",
      "currentGM": "$0",
      "currentGMPct": "0.0%",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CATFOOD",
      "currentVolume": "0",
      "sizeClass": "X-SMALL",
      "sizeFamily": "SPCL CARE URINARY",
      "brand": "PURINA_SPCLCARE",
      "brandClass": "NATIONAL BRAND",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "strategyRunId": "55",
      "lineGroup": "00001780001278",
      "customerLocationKey": "000117",
      "countBrokenRules": "0",
      "isPrePriced": 0,
      "cost": "$12.84",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "23598",
      "priceEffectiveDate":"May 20, 2021",
      "dropdownTest":2,
      "numbersRoundedTo2Decimals" : 12.4234234234,
      "numbersCurrencyRoundedTo2Decimals" : 12.4234234234,
    },
    {
      "upc": "00003470058410",
      "progress": .99,
      "opportunity":.94,
      "comboDropdownTest":"FRED",
      "rowDependentDropdown" :"",
      "priceEffectiveDate":"5/20/2021",
      "locationName": "SINTON",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": true,
      "productName": "ALLEN S PURPLE HULL PEAS",
      "size": "16",
      "uom": "OZ",
      "zone": "ZONE 131",
      "currentPrice": "$0.45",
      "lastApprovedPrice": "$2.30",
      "currentSales": "$26",
      "currentGM": "$3",
      "currentGMPct": "12.6%",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CANNEDDRYSOAKBEANS",
      "currentVolume": "57",
      "brand": "ALLENS",
      "brandClass": "NATIONAL",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "lastApprovedPricePerUOM": "$0.15",
      "strategyRunId": "55",
      "lineGroup": "00003470058410",
      "customerLocationKey": "000115",
      "countBrokenRules": "0",
      "lastApprovedDate": "Nov 30, 2020 8:47:24 PM",
      "isPrePriced": 0,
      "attribute0": "GROCERY",
      "attribute1": "N",
      "attribute2": "CANNED DRY SOAK BEANS",
      "cost": "$0.39",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "6072",
      "numbersRoundedTo2Decimals" : 2.45344,
      "numbersCurrencyRoundedTo2Decimals" : 2.45344,
    },
    {
      "disabled":true,
      "upc": "00003470058410",
      "progress": .98,
      "opportunity":.93,
      "comboDropdownTest":"ETHEL",
      "rowDependentDropdown" :"hello6074",
      "locationName": "CC12 WEBER/HOLLY",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": true,
      "productName": "ALLEN S PURPLE HULL PEAS",
      "size": "16",
      "uom": "OZ",
      "zone": "ZONE 131",
      "currentPrice": "$0.45",
      "lastApprovedPrice": "$2.30",
      "currentSales": "$50",
      "currentGM": "$6",
      "currentGMPct": "12.6%",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CANNEDDRYSOAKBEANS",
      "currentVolume": "110",
      "brand": "ALLENS",
      "brandClass": "NATIONAL",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "lastApprovedPricePerUOM": "$0.15",
      "strategyRunId": "55",
      "lineGroup": "00003470058410",
      "customerLocationKey": "000139",
      "countBrokenRules": "0",
      "lastApprovedDate": "Nov 30, 2020 8:47:24 PM",
      "isPrePriced": 0,
      "attribute0": "GROCERY",
      "attribute1": "N",
      "attribute2": "CANNED DRY SOAK BEANS",
      "cost": "$0.39",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "6074",
      "numbersRoundedTo2Decimals" : 5.42344,
      "numbersCurrencyRoundedTo2Decimals" : 5.42344,
    },
    {
      "upc": "00003470058410",
      "locationName": "KENEDY",
      "progress": .97,
      "opportunity":.90,
      "comboDropdownTest":"Merideth",
      "rowDependentDropdown" :"hi6076",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": true,
      "productName": "ALLEN S PURPLE HULL PEAS",
      "size": "16",
      "uom": "OZ",
      "zone": "ZONE 131",
      "currentPrice": "$0.45",
      "lastApprovedPrice": "$2.30",
      "currentSales": "$42",
      "currentGM": "$5",
      "currentGMPct": "12.6%",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CANNEDDRYSOAKBEANS",
      "currentVolume": "93",
      "brand": "ALLENS",
      "brandClass": "NATIONAL",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "lastApprovedPricePerUOM": "$0.15",
      "strategyRunId": "55",
      "lineGroup": "00003470058410",
      "customerLocationKey": "000155",
      "countBrokenRules": "0",
      "lastApprovedDate": "Nov 30, 2020 8:47:24 PM",
      "isPrePriced": 0,
      "attribute0": "GROCERY",
      "attribute1": "N",
      "attribute2": "CANNED DRY SOAK BEANS",
      "cost": "$0.39",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "6076",
      "numbersRoundedTo2Decimals" : 15.42344,
      "numbersCurrencyRoundedTo2Decimals" : 15.42344,
    },
    {
      "upc": "00003470058410",
      "locationName": "MATHIS",
      "progress": .89,
      "opportunity":.89,
      "comboDropdownTest":"ViCtoria",
      "rowDependentDropdown" :"hello6078",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": true,
      "productName": "ALLEN S PURPLE HULL PEAS",
      "size": "16",
      "uom": "OZ",
      "zone": "ZONE 131",
      "currentPrice": "$0.45",
      "lastApprovedPrice": "$2.30",
      "currentSales": "$39",
      "currentGM": "$5",
      "currentGMPct": "12.6%",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CANNEDDRYSOAKBEANS",
      "currentVolume": "86",
      "brand": "ALLENS",
      "brandClass": "NATIONAL",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "lastApprovedPricePerUOM": "$0.15",
      "strategyRunId": "55",
      "lineGroup": "00003470058410",
      "customerLocationKey": "000160",
      "countBrokenRules": "0",
      "lastApprovedDate": "Nov 30, 2020 8:47:24 PM",
      "isPrePriced": 0,
      "attribute0": "GROCERY",
      "attribute1": "N",
      "attribute2": "CANNED DRY SOAK BEANS",
      "cost": "$0.39",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "6078",
      "numbersRoundedTo2Decimals" : 0.4,
      "numbersCurrencyRoundedTo2Decimals" : 0.4
    },
    {
      "upc": "00003470058410",
      "locationName": "FALFURRIAS",
      "progress": .7,
      "opportunity":.70,
      "comboDropdownTest":"Elizabeth",
      "rowDependentDropdown" :"hello6079",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": true,
      "productName": "ALLEN S PURPLE HULL PEAS",
      "size": "16",
      "uom": "OZ",
      "zone": "ZONE 131",
      "currentPrice": "$0.45",
      "lastApprovedPrice": "$2.30",
      "currentSales": "$37",
      "currentGM": "$5",
      "currentGMPct": "12.6%",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CANNEDDRYSOAKBEANS",
      "currentVolume": "83",
      "brand": "ALLENS",
      "brandClass": "NATIONAL",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "lastApprovedPricePerUOM": "$0.15",
      "strategyRunId": "55",
      "lineGroup": "00003470058410",
      "customerLocationKey": "000200",
      "countBrokenRules": "0",
      "lastApprovedDate": "Nov 30, 2020 8:47:24 PM",
      "isPrePriced": 0,
      "attribute0": "GROCERY",
      "attribute1": "N",
      "attribute2": "CANNED DRY SOAK BEANS",
      "cost": "$0.39",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "6079",
      "numbersRoundedTo2Decimals" : 0.494,
      "numbersCurrencyRoundedTo2Decimals" : 0.494
    },
    {
      "upc": "00003470058410",
      "locationName": "CC18 SPID/WALDRON",
      "progress": .69,
      "opportunity":.65,
      "comboDropdownTest":"Graham",
      "rowDependentDropdown" :"hi6080",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": true,
      "productName": "ALLEN S PURPLE HULL PEAS",
      "size": "16",
      "uom": "OZ",
      "zone": "ZONE 131",
      "currentPrice": "$0.45",
      "lastApprovedPrice": "$2.30",
      "currentSales": "$103",
      "currentGM": "($13)",
      "currentGMPct": "(12.6%)",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CANNEDDRYSOAKBEANS",
      "currentVolume": "230",
      "brand": "ALLENS",
      "brandClass": "NATIONAL",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "lastApprovedPricePerUOM": "$0.15",
      "strategyRunId": "55",
      "lineGroup": "00003470058410",
      "customerLocationKey": "000204",
      "countBrokenRules": "0",
      "lastApprovedDate": "Nov 30, 2020 8:47:24 PM",
      "isPrePriced": 0,
      "attribute0": "GROCERY",
      "attribute1": "N",
      "attribute2": "CANNED DRY SOAK BEANS",
      "cost": "$0.39",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "6080",
      "numbersRoundedTo2Decimals" : 0.495,
      "numbersCurrencyRoundedTo2Decimals" : 0.495

    },
    {
      "upc": "00003470058410",
      "locationName": "CC06 ALAMEDA/ROBERTS",
      "progress": .68,
      "opportunity":.68,
      "comboDropdownTest":"Sylvia",
      "rowDependentDropdown" :"hi6081",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": true,
      "productName": "ALLEN S PURPLE HULL PEAS",
      "size": "16",
      "uom": "OZ",
      "zone": "ZONE 131",
      "currentPrice": "$0.45",
      "lastApprovedPrice": "$2.30",
      "currentSales": "$63",
      "currentGM": "$8",
      "currentGMPct": "12.6%",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CANNEDDRYSOAKBEANS",
      "currentVolume": "139",
      "brand": "ALLENS",
      "brandClass": "NATIONAL",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "lastApprovedPricePerUOM": "$0.15",
      "strategyRunId": "55",
      "lineGroup": "00003470058410",
      "customerLocationKey": "000210",
      "countBrokenRules": "0",
      "lastApprovedDate": "Nov 30, 2020 8:47:24 PM",
      "isPrePriced": 0,
      "attribute0": "GROCERY",
      "attribute1": "N",
      "attribute2": "CANNED DRY SOAK BEANS",
      "cost": "$0.39",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "6081",
      "numbersRoundedTo2Decimals" : 0.496,
      "numbersCurrencyRoundedTo2Decimals" : 0.496
    },
    {
      "upc": "00001780001278",
      "progress": 1,
      "opportunity":.95,
      "comboDropdownTest":"George",
      "rowDependentDropdown" :"hi23598",
      "locationName": "CRYSTAL CITY",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": false,
      "productName": "PURINA ONE URINARY 16LB",
      "size": "16",
      "uom": "LB",
      "zone": "ZONE 130",
      "currentPrice": "$0.00",
      "currentSales": "$0",
      "currentGM": "$0",
      "currentGMPct": "0.0%",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CATFOOD",
      "currentVolume": "0",
      "sizeClass": "X-SMALL",
      "sizeFamily": "SPCL CARE URINARY",
      "brand": "PURINA_SPCLCARE",
      "brandClass": "NATIONAL BRAND",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "strategyRunId": "55",
      "lineGroup": "00001780001278",
      "customerLocationKey": "000117",
      "countBrokenRules": "0",
      "isPrePriced": 0,
      "cost": "$12.84",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "23598",
      "priceEffectiveDate":"May 20, 2021",
      "dropdownTest":2,
      "numbersRoundedTo2Decimals" : 12.4234234234,
      "numbersCurrencyRoundedTo2Decimals" : 12.4234234234,
    },
    {
      "upc": "00003470058410",
      "progress": .99,
      "opportunity":.94,
      "comboDropdownTest":"FRED",
      "rowDependentDropdown" :"",
      "priceEffectiveDate":"5/20/2021",
      "locationName": "SINTON",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": true,
      "productName": "ALLEN S PURPLE HULL PEAS",
      "size": "16",
      "uom": "OZ",
      "zone": "ZONE 131",
      "currentPrice": "$0.45",
      "lastApprovedPrice": "$2.30",
      "currentSales": "$26",
      "currentGM": "$3",
      "currentGMPct": "12.6%",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CANNEDDRYSOAKBEANS",
      "currentVolume": "57",
      "brand": "ALLENS",
      "brandClass": "NATIONAL",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "lastApprovedPricePerUOM": "$0.15",
      "strategyRunId": "55",
      "lineGroup": "00003470058410",
      "customerLocationKey": "000115",
      "countBrokenRules": "0",
      "lastApprovedDate": "Nov 30, 2020 8:47:24 PM",
      "isPrePriced": 0,
      "attribute0": "GROCERY",
      "attribute1": "N",
      "attribute2": "CANNED DRY SOAK BEANS",
      "cost": "$0.39",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "6072",
      "numbersRoundedTo2Decimals" : 2.45344,
      "numbersCurrencyRoundedTo2Decimals" : 2.45344,
    },
    {
      "disabled":true,
      "upc": "00003470058410",
      "progress": .98,
      "opportunity":.93,
      "comboDropdownTest":"ETHEL",
      "rowDependentDropdown" :"hello6074",
      "locationName": "CC12 WEBER/HOLLY",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": true,
      "productName": "ALLEN S PURPLE HULL PEAS",
      "size": "16",
      "uom": "OZ",
      "zone": "ZONE 131",
      "currentPrice": "$0.45",
      "lastApprovedPrice": "$2.30",
      "currentSales": "$50",
      "currentGM": "$6",
      "currentGMPct": "12.6%",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CANNEDDRYSOAKBEANS",
      "currentVolume": "110",
      "brand": "ALLENS",
      "brandClass": "NATIONAL",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "lastApprovedPricePerUOM": "$0.15",
      "strategyRunId": "55",
      "lineGroup": "00003470058410",
      "customerLocationKey": "000139",
      "countBrokenRules": "0",
      "lastApprovedDate": "Nov 30, 2020 8:47:24 PM",
      "isPrePriced": 0,
      "attribute0": "GROCERY",
      "attribute1": "N",
      "attribute2": "CANNED DRY SOAK BEANS",
      "cost": "$0.39",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "6074",
      "numbersRoundedTo2Decimals" : 5.42344,
      "numbersCurrencyRoundedTo2Decimals" : 5.42344,
    },
    {
      "upc": "00003470058410",
      "locationName": "KENEDY",
      "progress": .97,
      "opportunity":.90,
      "comboDropdownTest":"Merideth",
      "rowDependentDropdown" :"hi6076",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": true,
      "productName": "ALLEN S PURPLE HULL PEAS",
      "size": "16",
      "uom": "OZ",
      "zone": "ZONE 131",
      "currentPrice": "$0.45",
      "lastApprovedPrice": "$2.30",
      "currentSales": "$42",
      "currentGM": "$5",
      "currentGMPct": "12.6%",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CANNEDDRYSOAKBEANS",
      "currentVolume": "93",
      "brand": "ALLENS",
      "brandClass": "NATIONAL",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "lastApprovedPricePerUOM": "$0.15",
      "strategyRunId": "55",
      "lineGroup": "00003470058410",
      "customerLocationKey": "000155",
      "countBrokenRules": "0",
      "lastApprovedDate": "Nov 30, 2020 8:47:24 PM",
      "isPrePriced": 0,
      "attribute0": "GROCERY",
      "attribute1": "N",
      "attribute2": "CANNED DRY SOAK BEANS",
      "cost": "$0.39",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "6076",
      "numbersRoundedTo2Decimals" : 15.42344,
      "numbersCurrencyRoundedTo2Decimals" : 15.42344,
    },
    {
      "upc": "00003470058410",
      "locationName": "MATHIS",
      "progress": .89,
      "opportunity":.89,
      "comboDropdownTest":"ViCtoria",
      "rowDependentDropdown" :"hello6078",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": true,
      "productName": "ALLEN S PURPLE HULL PEAS",
      "size": "16",
      "uom": "OZ",
      "zone": "ZONE 131",
      "currentPrice": "$0.45",
      "lastApprovedPrice": "$2.30",
      "currentSales": "$39",
      "currentGM": "$5",
      "currentGMPct": "12.6%",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CANNEDDRYSOAKBEANS",
      "currentVolume": "86",
      "brand": "ALLENS",
      "brandClass": "NATIONAL",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "lastApprovedPricePerUOM": "$0.15",
      "strategyRunId": "55",
      "lineGroup": "00003470058410",
      "customerLocationKey": "000160",
      "countBrokenRules": "0",
      "lastApprovedDate": "Nov 30, 2020 8:47:24 PM",
      "isPrePriced": 0,
      "attribute0": "GROCERY",
      "attribute1": "N",
      "attribute2": "CANNED DRY SOAK BEANS",
      "cost": "$0.39",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "6078",
      "numbersRoundedTo2Decimals" : 0.4,
      "numbersCurrencyRoundedTo2Decimals" : 0.4
    },
    {
      "upc": "00003470058410",
      "locationName": "FALFURRIAS",
      "progress": .7,
      "opportunity":.70,
      "comboDropdownTest":"Elizabeth",
      "rowDependentDropdown" :"hello6079",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": true,
      "productName": "ALLEN S PURPLE HULL PEAS",
      "size": "16",
      "uom": "OZ",
      "zone": "ZONE 131",
      "currentPrice": "$0.45",
      "lastApprovedPrice": "$2.30",
      "currentSales": "$37",
      "currentGM": "$5",
      "currentGMPct": "12.6%",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CANNEDDRYSOAKBEANS",
      "currentVolume": "83",
      "brand": "ALLENS",
      "brandClass": "NATIONAL",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "lastApprovedPricePerUOM": "$0.15",
      "strategyRunId": "55",
      "lineGroup": "00003470058410",
      "customerLocationKey": "000200",
      "countBrokenRules": "0",
      "lastApprovedDate": "Nov 30, 2020 8:47:24 PM",
      "isPrePriced": 0,
      "attribute0": "GROCERY",
      "attribute1": "N",
      "attribute2": "CANNED DRY SOAK BEANS",
      "cost": "$0.39",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "6079",
      "numbersRoundedTo2Decimals" : 0.494,
      "numbersCurrencyRoundedTo2Decimals" : 0.494
    },
    {
      "upc": "00003470058410",
      "locationName": "CC18 SPID/WALDRON",
      "progress": .69,
      "opportunity":.65,
      "comboDropdownTest":"Graham",
      "rowDependentDropdown" :"hi6080",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": true,
      "productName": "ALLEN S PURPLE HULL PEAS",
      "size": "16",
      "uom": "OZ",
      "zone": "ZONE 131",
      "currentPrice": "$0.45",
      "lastApprovedPrice": "$2.30",
      "currentSales": "$103",
      "currentGM": "($13)",
      "currentGMPct": "(12.6%)",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CANNEDDRYSOAKBEANS",
      "currentVolume": "230",
      "brand": "ALLENS",
      "brandClass": "NATIONAL",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "lastApprovedPricePerUOM": "$0.15",
      "strategyRunId": "55",
      "lineGroup": "00003470058410",
      "customerLocationKey": "000204",
      "countBrokenRules": "0",
      "lastApprovedDate": "Nov 30, 2020 8:47:24 PM",
      "isPrePriced": 0,
      "attribute0": "GROCERY",
      "attribute1": "N",
      "attribute2": "CANNED DRY SOAK BEANS",
      "cost": "$0.39",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "6080",
      "numbersRoundedTo2Decimals" : 0.495,
      "numbersCurrencyRoundedTo2Decimals" : 0.495

    },
    {
      "upc": "00003470058410",
      "locationName": "CC06 ALAMEDA/ROBERTS",
      "progress": .68,
      "opportunity":.68,
      "comboDropdownTest":"Sylvia",
      "rowDependentDropdown" :"hi6081",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": true,
      "productName": "ALLEN S PURPLE HULL PEAS",
      "size": "16",
      "uom": "OZ",
      "zone": "ZONE 131",
      "currentPrice": "$0.45",
      "lastApprovedPrice": "$2.30",
      "currentSales": "$63",
      "currentGM": "$8",
      "currentGMPct": "12.6%",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CANNEDDRYSOAKBEANS",
      "currentVolume": "139",
      "brand": "ALLENS",
      "brandClass": "NATIONAL",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "lastApprovedPricePerUOM": "$0.15",
      "strategyRunId": "55",
      "lineGroup": "00003470058410",
      "customerLocationKey": "000210",
      "countBrokenRules": "0",
      "lastApprovedDate": "Nov 30, 2020 8:47:24 PM",
      "isPrePriced": 0,
      "attribute0": "GROCERY",
      "attribute1": "N",
      "attribute2": "CANNED DRY SOAK BEANS",
      "cost": "$0.39",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "6081",
      "numbersRoundedTo2Decimals" : 0.496,
      "numbersCurrencyRoundedTo2Decimals" : 0.496
    },
    {
      "upc": "00001780001278",
      "progress": 1,
      "opportunity":.95,
      "comboDropdownTest":"George",
      "rowDependentDropdown" :"hi23598",
      "locationName": "CRYSTAL CITY",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": false,
      "productName": "PURINA ONE URINARY 16LB",
      "size": "16",
      "uom": "LB",
      "zone": "ZONE 130",
      "currentPrice": "$0.00",
      "currentSales": "$0",
      "currentGM": "$0",
      "currentGMPct": "0.0%",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CATFOOD",
      "currentVolume": "0",
      "sizeClass": "X-SMALL",
      "sizeFamily": "SPCL CARE URINARY",
      "brand": "PURINA_SPCLCARE",
      "brandClass": "NATIONAL BRAND",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "strategyRunId": "55",
      "lineGroup": "00001780001278",
      "customerLocationKey": "000117",
      "countBrokenRules": "0",
      "isPrePriced": 0,
      "cost": "$12.84",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "23598",
      "priceEffectiveDate":"May 20, 2021",
      "dropdownTest":2,
      "numbersRoundedTo2Decimals" : 12.4234234234,
      "numbersCurrencyRoundedTo2Decimals" : 12.4234234234,
    },
    {
      "upc": "00003470058410",
      "progress": .99,
      "opportunity":.94,
      "comboDropdownTest":"FRED",
      "rowDependentDropdown" :"",
      "priceEffectiveDate":"5/20/2021",
      "locationName": "SINTON",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": true,
      "productName": "ALLEN S PURPLE HULL PEAS",
      "size": "16",
      "uom": "OZ",
      "zone": "ZONE 131",
      "currentPrice": "$0.45",
      "lastApprovedPrice": "$2.30",
      "currentSales": "$26",
      "currentGM": "$3",
      "currentGMPct": "12.6%",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CANNEDDRYSOAKBEANS",
      "currentVolume": "57",
      "brand": "ALLENS",
      "brandClass": "NATIONAL",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "lastApprovedPricePerUOM": "$0.15",
      "strategyRunId": "55",
      "lineGroup": "00003470058410",
      "customerLocationKey": "000115",
      "countBrokenRules": "0",
      "lastApprovedDate": "Nov 30, 2020 8:47:24 PM",
      "isPrePriced": 0,
      "attribute0": "GROCERY",
      "attribute1": "N",
      "attribute2": "CANNED DRY SOAK BEANS",
      "cost": "$0.39",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "6072",
      "numbersRoundedTo2Decimals" : 2.45344,
      "numbersCurrencyRoundedTo2Decimals" : 2.45344,
    },
    {
      "disabled":true,
      "upc": "00003470058410",
      "progress": .98,
      "opportunity":.93,
      "comboDropdownTest":"ETHEL",
      "rowDependentDropdown" :"hello6074",
      "locationName": "CC12 WEBER/HOLLY",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": true,
      "productName": "ALLEN S PURPLE HULL PEAS",
      "size": "16",
      "uom": "OZ",
      "zone": "ZONE 131",
      "currentPrice": "$0.45",
      "lastApprovedPrice": "$2.30",
      "currentSales": "$50",
      "currentGM": "$6",
      "currentGMPct": "12.6%",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CANNEDDRYSOAKBEANS",
      "currentVolume": "110",
      "brand": "ALLENS",
      "brandClass": "NATIONAL",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "lastApprovedPricePerUOM": "$0.15",
      "strategyRunId": "55",
      "lineGroup": "00003470058410",
      "customerLocationKey": "000139",
      "countBrokenRules": "0",
      "lastApprovedDate": "Nov 30, 2020 8:47:24 PM",
      "isPrePriced": 0,
      "attribute0": "GROCERY",
      "attribute1": "N",
      "attribute2": "CANNED DRY SOAK BEANS",
      "cost": "$0.39",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "6074",
      "numbersRoundedTo2Decimals" : 5.42344,
      "numbersCurrencyRoundedTo2Decimals" : 5.42344,
    },
    {
      "upc": "00003470058410",
      "locationName": "KENEDY",
      "progress": .97,
      "opportunity":.90,
      "comboDropdownTest":"Merideth",
      "rowDependentDropdown" :"hi6076",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": true,
      "productName": "ALLEN S PURPLE HULL PEAS",
      "size": "16",
      "uom": "OZ",
      "zone": "ZONE 131",
      "currentPrice": "$0.45",
      "lastApprovedPrice": "$2.30",
      "currentSales": "$42",
      "currentGM": "$5",
      "currentGMPct": "12.6%",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CANNEDDRYSOAKBEANS",
      "currentVolume": "93",
      "brand": "ALLENS",
      "brandClass": "NATIONAL",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "lastApprovedPricePerUOM": "$0.15",
      "strategyRunId": "55",
      "lineGroup": "00003470058410",
      "customerLocationKey": "000155",
      "countBrokenRules": "0",
      "lastApprovedDate": "Nov 30, 2020 8:47:24 PM",
      "isPrePriced": 0,
      "attribute0": "GROCERY",
      "attribute1": "N",
      "attribute2": "CANNED DRY SOAK BEANS",
      "cost": "$0.39",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "6076",
      "numbersRoundedTo2Decimals" : 15.42344,
      "numbersCurrencyRoundedTo2Decimals" : 15.42344,
    },
    {
      "upc": "00003470058410",
      "locationName": "MATHIS",
      "progress": .89,
      "opportunity":.89,
      "comboDropdownTest":"ViCtoria",
      "rowDependentDropdown" :"hello6078",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": true,
      "productName": "ALLEN S PURPLE HULL PEAS",
      "size": "16",
      "uom": "OZ",
      "zone": "ZONE 131",
      "currentPrice": "$0.45",
      "lastApprovedPrice": "$2.30",
      "currentSales": "$39",
      "currentGM": "$5",
      "currentGMPct": "12.6%",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CANNEDDRYSOAKBEANS",
      "currentVolume": "86",
      "brand": "ALLENS",
      "brandClass": "NATIONAL",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "lastApprovedPricePerUOM": "$0.15",
      "strategyRunId": "55",
      "lineGroup": "00003470058410",
      "customerLocationKey": "000160",
      "countBrokenRules": "0",
      "lastApprovedDate": "Nov 30, 2020 8:47:24 PM",
      "isPrePriced": 0,
      "attribute0": "GROCERY",
      "attribute1": "N",
      "attribute2": "CANNED DRY SOAK BEANS",
      "cost": "$0.39",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "6078",
      "numbersRoundedTo2Decimals" : 0.4,
      "numbersCurrencyRoundedTo2Decimals" : 0.4
    },
    {
      "upc": "00003470058410",
      "locationName": "FALFURRIAS",
      "progress": .7,
      "opportunity":.70,
      "comboDropdownTest":"Elizabeth",
      "rowDependentDropdown" :"hello6079",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": true,
      "productName": "ALLEN S PURPLE HULL PEAS",
      "size": "16",
      "uom": "OZ",
      "zone": "ZONE 131",
      "currentPrice": "$0.45",
      "lastApprovedPrice": "$2.30",
      "currentSales": "$37",
      "currentGM": "$5",
      "currentGMPct": "12.6%",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CANNEDDRYSOAKBEANS",
      "currentVolume": "83",
      "brand": "ALLENS",
      "brandClass": "NATIONAL",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "lastApprovedPricePerUOM": "$0.15",
      "strategyRunId": "55",
      "lineGroup": "00003470058410",
      "customerLocationKey": "000200",
      "countBrokenRules": "0",
      "lastApprovedDate": "Nov 30, 2020 8:47:24 PM",
      "isPrePriced": 0,
      "attribute0": "GROCERY",
      "attribute1": "N",
      "attribute2": "CANNED DRY SOAK BEANS",
      "cost": "$0.39",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "6079",
      "numbersRoundedTo2Decimals" : 0.494,
      "numbersCurrencyRoundedTo2Decimals" : 0.494
    },
    {
      "upc": "00003470058410",
      "locationName": "CC18 SPID/WALDRON",
      "progress": .69,
      "opportunity":.65,
      "comboDropdownTest":"Graham",
      "rowDependentDropdown" :"hi6080",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": true,
      "productName": "ALLEN S PURPLE HULL PEAS",
      "size": "16",
      "uom": "OZ",
      "zone": "ZONE 131",
      "currentPrice": "$0.45",
      "lastApprovedPrice": "$2.30",
      "currentSales": "$103",
      "currentGM": "($13)",
      "currentGMPct": "(12.6%)",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CANNEDDRYSOAKBEANS",
      "currentVolume": "230",
      "brand": "ALLENS",
      "brandClass": "NATIONAL",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "lastApprovedPricePerUOM": "$0.15",
      "strategyRunId": "55",
      "lineGroup": "00003470058410",
      "customerLocationKey": "000204",
      "countBrokenRules": "0",
      "lastApprovedDate": "Nov 30, 2020 8:47:24 PM",
      "isPrePriced": 0,
      "attribute0": "GROCERY",
      "attribute1": "N",
      "attribute2": "CANNED DRY SOAK BEANS",
      "cost": "$0.39",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "6080",
      "numbersRoundedTo2Decimals" : 0.495,
      "numbersCurrencyRoundedTo2Decimals" : 0.495

    },
    {
      "upc": "00003470058410",
      "locationName": "CC06 ALAMEDA/ROBERTS",
      "progress": .68,
      "opportunity":.68,
      "comboDropdownTest":"Sylvia",
      "rowDependentDropdown" :"hi6081",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": true,
      "productName": "ALLEN S PURPLE HULL PEAS",
      "size": "16",
      "uom": "OZ",
      "zone": "ZONE 131",
      "currentPrice": "$0.45",
      "lastApprovedPrice": "$2.30",
      "currentSales": "$63",
      "currentGM": "$8",
      "currentGMPct": "12.6%",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CANNEDDRYSOAKBEANS",
      "currentVolume": "139",
      "brand": "ALLENS",
      "brandClass": "NATIONAL",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "lastApprovedPricePerUOM": "$0.15",
      "strategyRunId": "55",
      "lineGroup": "00003470058410",
      "customerLocationKey": "000210",
      "countBrokenRules": "0",
      "lastApprovedDate": "Nov 30, 2020 8:47:24 PM",
      "isPrePriced": 0,
      "attribute0": "GROCERY",
      "attribute1": "N",
      "attribute2": "CANNED DRY SOAK BEANS",
      "cost": "$0.39",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "6081",
      "numbersRoundedTo2Decimals" : 0.496,
      "numbersCurrencyRoundedTo2Decimals" : 0.496
    },
    {
      "upc": "00001780001278",
      "progress": 1,
      "opportunity":.95,
      "comboDropdownTest":"George",
      "rowDependentDropdown" :"hi23598",
      "locationName": "CRYSTAL CITY",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": false,
      "productName": "PURINA ONE URINARY 16LB",
      "size": "16",
      "uom": "LB",
      "zone": "ZONE 130",
      "currentPrice": "$0.00",
      "currentSales": "$0",
      "currentGM": "$0",
      "currentGMPct": "0.0%",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CATFOOD",
      "currentVolume": "0",
      "sizeClass": "X-SMALL",
      "sizeFamily": "SPCL CARE URINARY",
      "brand": "PURINA_SPCLCARE",
      "brandClass": "NATIONAL BRAND",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "strategyRunId": "55",
      "lineGroup": "00001780001278",
      "customerLocationKey": "000117",
      "countBrokenRules": "0",
      "isPrePriced": 0,
      "cost": "$12.84",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "23598",
      "priceEffectiveDate":"May 20, 2021",
      "dropdownTest":2,
      "numbersRoundedTo2Decimals" : 12.4234234234,
      "numbersCurrencyRoundedTo2Decimals" : 12.4234234234,
    },
    {
      "upc": "00003470058410",
      "progress": .99,
      "opportunity":.94,
      "comboDropdownTest":"FRED",
      "rowDependentDropdown" :"",
      "priceEffectiveDate":"5/20/2021",
      "locationName": "SINTON",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": true,
      "productName": "ALLEN S PURPLE HULL PEAS",
      "size": "16",
      "uom": "OZ",
      "zone": "ZONE 131",
      "currentPrice": "$0.45",
      "lastApprovedPrice": "$2.30",
      "currentSales": "$26",
      "currentGM": "$3",
      "currentGMPct": "12.6%",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CANNEDDRYSOAKBEANS",
      "currentVolume": "57",
      "brand": "ALLENS",
      "brandClass": "NATIONAL",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "lastApprovedPricePerUOM": "$0.15",
      "strategyRunId": "55",
      "lineGroup": "00003470058410",
      "customerLocationKey": "000115",
      "countBrokenRules": "0",
      "lastApprovedDate": "Nov 30, 2020 8:47:24 PM",
      "isPrePriced": 0,
      "attribute0": "GROCERY",
      "attribute1": "N",
      "attribute2": "CANNED DRY SOAK BEANS",
      "cost": "$0.39",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "6072",
      "numbersRoundedTo2Decimals" : 2.45344,
      "numbersCurrencyRoundedTo2Decimals" : 2.45344,
    },
    {
      "disabled":true,
      "upc": "00003470058410",
      "progress": .98,
      "opportunity":.93,
      "comboDropdownTest":"ETHEL",
      "rowDependentDropdown" :"hello6074",
      "locationName": "CC12 WEBER/HOLLY",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": true,
      "productName": "ALLEN S PURPLE HULL PEAS",
      "size": "16",
      "uom": "OZ",
      "zone": "ZONE 131",
      "currentPrice": "$0.45",
      "lastApprovedPrice": "$2.30",
      "currentSales": "$50",
      "currentGM": "$6",
      "currentGMPct": "12.6%",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CANNEDDRYSOAKBEANS",
      "currentVolume": "110",
      "brand": "ALLENS",
      "brandClass": "NATIONAL",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "lastApprovedPricePerUOM": "$0.15",
      "strategyRunId": "55",
      "lineGroup": "00003470058410",
      "customerLocationKey": "000139",
      "countBrokenRules": "0",
      "lastApprovedDate": "Nov 30, 2020 8:47:24 PM",
      "isPrePriced": 0,
      "attribute0": "GROCERY",
      "attribute1": "N",
      "attribute2": "CANNED DRY SOAK BEANS",
      "cost": "$0.39",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "6074",
      "numbersRoundedTo2Decimals" : 5.42344,
      "numbersCurrencyRoundedTo2Decimals" : 5.42344,
    },
    {
      "upc": "00003470058410",
      "locationName": "KENEDY",
      "progress": .97,
      "opportunity":.90,
      "comboDropdownTest":"Merideth",
      "rowDependentDropdown" :"hi6076",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": true,
      "productName": "ALLEN S PURPLE HULL PEAS",
      "size": "16",
      "uom": "OZ",
      "zone": "ZONE 131",
      "currentPrice": "$0.45",
      "lastApprovedPrice": "$2.30",
      "currentSales": "$42",
      "currentGM": "$5",
      "currentGMPct": "12.6%",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CANNEDDRYSOAKBEANS",
      "currentVolume": "93",
      "brand": "ALLENS",
      "brandClass": "NATIONAL",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "lastApprovedPricePerUOM": "$0.15",
      "strategyRunId": "55",
      "lineGroup": "00003470058410",
      "customerLocationKey": "000155",
      "countBrokenRules": "0",
      "lastApprovedDate": "Nov 30, 2020 8:47:24 PM",
      "isPrePriced": 0,
      "attribute0": "GROCERY",
      "attribute1": "N",
      "attribute2": "CANNED DRY SOAK BEANS",
      "cost": "$0.39",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "6076",
      "numbersRoundedTo2Decimals" : 15.42344,
      "numbersCurrencyRoundedTo2Decimals" : 15.42344,
    },
    {
      "upc": "00003470058410",
      "locationName": "MATHIS",
      "progress": .89,
      "opportunity":.89,
      "comboDropdownTest":"ViCtoria",
      "rowDependentDropdown" :"hello6078",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": true,
      "productName": "ALLEN S PURPLE HULL PEAS",
      "size": "16",
      "uom": "OZ",
      "zone": "ZONE 131",
      "currentPrice": "$0.45",
      "lastApprovedPrice": "$2.30",
      "currentSales": "$39",
      "currentGM": "$5",
      "currentGMPct": "12.6%",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CANNEDDRYSOAKBEANS",
      "currentVolume": "86",
      "brand": "ALLENS",
      "brandClass": "NATIONAL",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "lastApprovedPricePerUOM": "$0.15",
      "strategyRunId": "55",
      "lineGroup": "00003470058410",
      "customerLocationKey": "000160",
      "countBrokenRules": "0",
      "lastApprovedDate": "Nov 30, 2020 8:47:24 PM",
      "isPrePriced": 0,
      "attribute0": "GROCERY",
      "attribute1": "N",
      "attribute2": "CANNED DRY SOAK BEANS",
      "cost": "$0.39",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "6078",
      "numbersRoundedTo2Decimals" : 0.4,
      "numbersCurrencyRoundedTo2Decimals" : 0.4
    },
    {
      "upc": "00003470058410",
      "locationName": "FALFURRIAS",
      "progress": .7,
      "opportunity":.70,
      "comboDropdownTest":"Elizabeth",
      "rowDependentDropdown" :"hello6079",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": true,
      "productName": "ALLEN S PURPLE HULL PEAS",
      "size": "16",
      "uom": "OZ",
      "zone": "ZONE 131",
      "currentPrice": "$0.45",
      "lastApprovedPrice": "$2.30",
      "currentSales": "$37",
      "currentGM": "$5",
      "currentGMPct": "12.6%",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CANNEDDRYSOAKBEANS",
      "currentVolume": "83",
      "brand": "ALLENS",
      "brandClass": "NATIONAL",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "lastApprovedPricePerUOM": "$0.15",
      "strategyRunId": "55",
      "lineGroup": "00003470058410",
      "customerLocationKey": "000200",
      "countBrokenRules": "0",
      "lastApprovedDate": "Nov 30, 2020 8:47:24 PM",
      "isPrePriced": 0,
      "attribute0": "GROCERY",
      "attribute1": "N",
      "attribute2": "CANNED DRY SOAK BEANS",
      "cost": "$0.39",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "6079",
      "numbersRoundedTo2Decimals" : 0.494,
      "numbersCurrencyRoundedTo2Decimals" : 0.494
    },
    {
      "upc": "00003470058410",
      "locationName": "CC18 SPID/WALDRON",
      "progress": .69,
      "opportunity":.65,
      "comboDropdownTest":"Graham",
      "rowDependentDropdown" :"hi6080",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": true,
      "productName": "ALLEN S PURPLE HULL PEAS",
      "size": "16",
      "uom": "OZ",
      "zone": "ZONE 131",
      "currentPrice": "$0.45",
      "lastApprovedPrice": "$2.30",
      "currentSales": "$103",
      "currentGM": "($13)",
      "currentGMPct": "(12.6%)",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CANNEDDRYSOAKBEANS",
      "currentVolume": "230",
      "brand": "ALLENS",
      "brandClass": "NATIONAL",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "lastApprovedPricePerUOM": "$0.15",
      "strategyRunId": "55",
      "lineGroup": "00003470058410",
      "customerLocationKey": "000204",
      "countBrokenRules": "0",
      "lastApprovedDate": "Nov 30, 2020 8:47:24 PM",
      "isPrePriced": 0,
      "attribute0": "GROCERY",
      "attribute1": "N",
      "attribute2": "CANNED DRY SOAK BEANS",
      "cost": "$0.39",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "6080",
      "numbersRoundedTo2Decimals" : 0.495,
      "numbersCurrencyRoundedTo2Decimals" : 0.495

    },
    {
      "upc": "00003470058410",
      "locationName": "CC06 ALAMEDA/ROBERTS",
      "progress": .68,
      "opportunity":.68,
      "comboDropdownTest":"Sylvia",
      "rowDependentDropdown" :"hi6081",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": true,
      "productName": "ALLEN S PURPLE HULL PEAS",
      "size": "16",
      "uom": "OZ",
      "zone": "ZONE 131",
      "currentPrice": "$0.45",
      "lastApprovedPrice": "$2.30",
      "currentSales": "$63",
      "currentGM": "$8",
      "currentGMPct": "12.6%",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CANNEDDRYSOAKBEANS",
      "currentVolume": "139",
      "brand": "ALLENS",
      "brandClass": "NATIONAL",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "lastApprovedPricePerUOM": "$0.15",
      "strategyRunId": "55",
      "lineGroup": "00003470058410",
      "customerLocationKey": "000210",
      "countBrokenRules": "0",
      "lastApprovedDate": "Nov 30, 2020 8:47:24 PM",
      "isPrePriced": 0,
      "attribute0": "GROCERY",
      "attribute1": "N",
      "attribute2": "CANNED DRY SOAK BEANS",
      "cost": "$0.39",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "6081",
      "numbersRoundedTo2Decimals" : 0.496,
      "numbersCurrencyRoundedTo2Decimals" : 0.496
    },
    {
      "upc": "00001780001278",
      "progress": 1,
      "opportunity":.95,
      "comboDropdownTest":"George",
      "rowDependentDropdown" :"hi23598",
      "locationName": "CRYSTAL CITY",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": false,
      "productName": "PURINA ONE URINARY 16LB",
      "size": "16",
      "uom": "LB",
      "zone": "ZONE 130",
      "currentPrice": "$0.00",
      "currentSales": "$0",
      "currentGM": "$0",
      "currentGMPct": "0.0%",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CATFOOD",
      "currentVolume": "0",
      "sizeClass": "X-SMALL",
      "sizeFamily": "SPCL CARE URINARY",
      "brand": "PURINA_SPCLCARE",
      "brandClass": "NATIONAL BRAND",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "strategyRunId": "55",
      "lineGroup": "00001780001278",
      "customerLocationKey": "000117",
      "countBrokenRules": "0",
      "isPrePriced": 0,
      "cost": "$12.84",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "23598",
      "priceEffectiveDate":"May 20, 2021",
      "dropdownTest":2,
      "numbersRoundedTo2Decimals" : 12.4234234234,
      "numbersCurrencyRoundedTo2Decimals" : 12.4234234234,
    },
    {
      "upc": "00003470058410",
      "progress": .99,
      "opportunity":.94,
      "comboDropdownTest":"FRED",
      "rowDependentDropdown" :"",
      "priceEffectiveDate":"5/20/2021",
      "locationName": "SINTON",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": true,
      "productName": "ALLEN S PURPLE HULL PEAS",
      "size": "16",
      "uom": "OZ",
      "zone": "ZONE 131",
      "currentPrice": "$0.45",
      "lastApprovedPrice": "$2.30",
      "currentSales": "$26",
      "currentGM": "$3",
      "currentGMPct": "12.6%",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CANNEDDRYSOAKBEANS",
      "currentVolume": "57",
      "brand": "ALLENS",
      "brandClass": "NATIONAL",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "lastApprovedPricePerUOM": "$0.15",
      "strategyRunId": "55",
      "lineGroup": "00003470058410",
      "customerLocationKey": "000115",
      "countBrokenRules": "0",
      "lastApprovedDate": "Nov 30, 2020 8:47:24 PM",
      "isPrePriced": 0,
      "attribute0": "GROCERY",
      "attribute1": "N",
      "attribute2": "CANNED DRY SOAK BEANS",
      "cost": "$0.39",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "6072",
      "numbersRoundedTo2Decimals" : 2.45344,
      "numbersCurrencyRoundedTo2Decimals" : 2.45344,
    },
    {
      "disabled":true,
      "upc": "00003470058410",
      "progress": .98,
      "opportunity":.93,
      "comboDropdownTest":"ETHEL",
      "rowDependentDropdown" :"hello6074",
      "locationName": "CC12 WEBER/HOLLY",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": true,
      "productName": "ALLEN S PURPLE HULL PEAS",
      "size": "16",
      "uom": "OZ",
      "zone": "ZONE 131",
      "currentPrice": "$0.45",
      "lastApprovedPrice": "$2.30",
      "currentSales": "$50",
      "currentGM": "$6",
      "currentGMPct": "12.6%",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CANNEDDRYSOAKBEANS",
      "currentVolume": "110",
      "brand": "ALLENS",
      "brandClass": "NATIONAL",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "lastApprovedPricePerUOM": "$0.15",
      "strategyRunId": "55",
      "lineGroup": "00003470058410",
      "customerLocationKey": "000139",
      "countBrokenRules": "0",
      "lastApprovedDate": "Nov 30, 2020 8:47:24 PM",
      "isPrePriced": 0,
      "attribute0": "GROCERY",
      "attribute1": "N",
      "attribute2": "CANNED DRY SOAK BEANS",
      "cost": "$0.39",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "6074",
      "numbersRoundedTo2Decimals" : 5.42344,
      "numbersCurrencyRoundedTo2Decimals" : 5.42344,
    },
    {
      "upc": "00003470058410",
      "locationName": "KENEDY",
      "progress": .97,
      "opportunity":.90,
      "comboDropdownTest":"Merideth",
      "rowDependentDropdown" :"hi6076",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": true,
      "productName": "ALLEN S PURPLE HULL PEAS",
      "size": "16",
      "uom": "OZ",
      "zone": "ZONE 131",
      "currentPrice": "$0.45",
      "lastApprovedPrice": "$2.30",
      "currentSales": "$42",
      "currentGM": "$5",
      "currentGMPct": "12.6%",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CANNEDDRYSOAKBEANS",
      "currentVolume": "93",
      "brand": "ALLENS",
      "brandClass": "NATIONAL",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "lastApprovedPricePerUOM": "$0.15",
      "strategyRunId": "55",
      "lineGroup": "00003470058410",
      "customerLocationKey": "000155",
      "countBrokenRules": "0",
      "lastApprovedDate": "Nov 30, 2020 8:47:24 PM",
      "isPrePriced": 0,
      "attribute0": "GROCERY",
      "attribute1": "N",
      "attribute2": "CANNED DRY SOAK BEANS",
      "cost": "$0.39",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "6076",
      "numbersRoundedTo2Decimals" : 15.42344,
      "numbersCurrencyRoundedTo2Decimals" : 15.42344,
    },
    {
      "upc": "00003470058410",
      "locationName": "MATHIS",
      "progress": .89,
      "opportunity":.89,
      "comboDropdownTest":"ViCtoria",
      "rowDependentDropdown" :"hello6078",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": true,
      "productName": "ALLEN S PURPLE HULL PEAS",
      "size": "16",
      "uom": "OZ",
      "zone": "ZONE 131",
      "currentPrice": "$0.45",
      "lastApprovedPrice": "$2.30",
      "currentSales": "$39",
      "currentGM": "$5",
      "currentGMPct": "12.6%",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CANNEDDRYSOAKBEANS",
      "currentVolume": "86",
      "brand": "ALLENS",
      "brandClass": "NATIONAL",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "lastApprovedPricePerUOM": "$0.15",
      "strategyRunId": "55",
      "lineGroup": "00003470058410",
      "customerLocationKey": "000160",
      "countBrokenRules": "0",
      "lastApprovedDate": "Nov 30, 2020 8:47:24 PM",
      "isPrePriced": 0,
      "attribute0": "GROCERY",
      "attribute1": "N",
      "attribute2": "CANNED DRY SOAK BEANS",
      "cost": "$0.39",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "6078",
      "numbersRoundedTo2Decimals" : 0.4,
      "numbersCurrencyRoundedTo2Decimals" : 0.4
    },
    {
      "upc": "00003470058410",
      "locationName": "FALFURRIAS",
      "progress": .7,
      "opportunity":.70,
      "comboDropdownTest":"Elizabeth",
      "rowDependentDropdown" :"hello6079",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": true,
      "productName": "ALLEN S PURPLE HULL PEAS",
      "size": "16",
      "uom": "OZ",
      "zone": "ZONE 131",
      "currentPrice": "$0.45",
      "lastApprovedPrice": "$2.30",
      "currentSales": "$37",
      "currentGM": "$5",
      "currentGMPct": "12.6%",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CANNEDDRYSOAKBEANS",
      "currentVolume": "83",
      "brand": "ALLENS",
      "brandClass": "NATIONAL",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "lastApprovedPricePerUOM": "$0.15",
      "strategyRunId": "55",
      "lineGroup": "00003470058410",
      "customerLocationKey": "000200",
      "countBrokenRules": "0",
      "lastApprovedDate": "Nov 30, 2020 8:47:24 PM",
      "isPrePriced": 0,
      "attribute0": "GROCERY",
      "attribute1": "N",
      "attribute2": "CANNED DRY SOAK BEANS",
      "cost": "$0.39",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "6079",
      "numbersRoundedTo2Decimals" : 0.494,
      "numbersCurrencyRoundedTo2Decimals" : 0.494
    },
    {
      "upc": "00003470058410",
      "locationName": "CC18 SPID/WALDRON",
      "progress": .69,
      "opportunity":.65,
      "comboDropdownTest":"Graham",
      "rowDependentDropdown" :"hi6080",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": true,
      "productName": "ALLEN S PURPLE HULL PEAS",
      "size": "16",
      "uom": "OZ",
      "zone": "ZONE 131",
      "currentPrice": "$0.45",
      "lastApprovedPrice": "$2.30",
      "currentSales": "$103",
      "currentGM": "($13)",
      "currentGMPct": "(12.6%)",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CANNEDDRYSOAKBEANS",
      "currentVolume": "230",
      "brand": "ALLENS",
      "brandClass": "NATIONAL",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "lastApprovedPricePerUOM": "$0.15",
      "strategyRunId": "55",
      "lineGroup": "00003470058410",
      "customerLocationKey": "000204",
      "countBrokenRules": "0",
      "lastApprovedDate": "Nov 30, 2020 8:47:24 PM",
      "isPrePriced": 0,
      "attribute0": "GROCERY",
      "attribute1": "N",
      "attribute2": "CANNED DRY SOAK BEANS",
      "cost": "$0.39",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "6080",
      "numbersRoundedTo2Decimals" : 0.495,
      "numbersCurrencyRoundedTo2Decimals" : 0.495

    },
    {
      "upc": "00003470058410",
      "locationName": "CC06 ALAMEDA/ROBERTS",
      "progress": .68,
      "opportunity":.68,
      "comboDropdownTest":"Sylvia",
      "rowDependentDropdown" :"hi6081",
      "approveStatus": "No Price Change-10",
      "isCompChange": "0",
      "productSelected": true,
      "productName": "ALLEN S PURPLE HULL PEAS",
      "size": "16",
      "uom": "OZ",
      "zone": "ZONE 131",
      "currentPrice": "$0.45",
      "lastApprovedPrice": "$2.30",
      "currentSales": "$63",
      "currentGM": "$8",
      "currentGMPct": "12.6%",
      "channel": "Brick & Mortar",
      "division": "Chain",
      "category": "CANNEDDRYSOAKBEANS",
      "currentVolume": "139",
      "brand": "ALLENS",
      "brandClass": "NATIONAL",
      "productRole": "Niche High Sensitivity",
      "strategyName": "developer Dec 11 2020 nnn",
      "lastApprovedPricePerUOM": "$0.15",
      "strategyRunId": "55",
      "lineGroup": "00003470058410",
      "customerLocationKey": "000210",
      "countBrokenRules": "0",
      "lastApprovedDate": "Nov 30, 2020 8:47:24 PM",
      "isPrePriced": 0,
      "attribute0": "GROCERY",
      "attribute1": "N",
      "attribute2": "CANNED DRY SOAK BEANS",
      "cost": "$0.39",
      "isDelivery": 0,
      "countApprovable": "0",
      "countCancelable": "0",
      "countDelivered": "0",
      "id": "6081",
      "numbersRoundedTo2Decimals" : 0.496,
      "numbersCurrencyRoundedTo2Decimals" : 0.496
    }
  ],
  "total": 48
}


const myconfig = [
  {
    "id": "upc",
    "title": "",
    "sortable": false,
    "format": "link",
    "dataType": "String",
    "dragLock": false,
    "defaultVisible": true,
    "requiredForUiState": false,
    "defaultWidth": 150,
    "filterable": false,
    "filterType" : "default",
    "headerKey": "upc",
    "isSortable": false,
    "order": 1,
    "visible": true
  },
  {
    "id": "locationName",
    "title": "Store Name",
    "sortable": false,
    "format": "string",
    "dataType": "String",
    "dragLock": false,
    "defaultVisible": true,
    "requiredForUiState": false,
    "defaultWidth": 160,
    "filterable": false,
    "filterType" : "default",
    "headerKey": "locationName",
    "isSortable": false,
    "order": 2,
    "visible": true
  },
  {
    "id": "overridePrice",
    "title": "Override Price",
    "sortable": false,
    "format": "currency",
    "dataType": "String",
    "dragLock": false,
    "editorType": "currency",
    "defaultVisible": true,
    "requiredForUiState": false,
    "defaultWidth": 140,
    "filterable": false,
    "filterType" : "range",
    "headerKey": "overridePrice",
    "isSortable": false,
    "isEditable": true,
    "order": 23,
    "visible": true
  },
  {
    "id": "overrideComment",
    "title": "Override Comment (dragLock)",
    "sortable": false,
    "format": "string",
    "dataType": "String",
    "dragLock": true,
    "editorType": "string",
    "defaultVisible": true,
    "requiredForUiState": false,
    "defaultWidth": 180,
    "filterable": false,
    "filterType" : "default",
    "headerKey": "overrideComment",
    "isSortable": false,
    "isEditable": true,
    "order": 24,
    "visible": true
  },
  {
    "id": "isNewProduct",
    "title": "Data Change",
    "sortable": false,
    "format": "set.tag.newproduct",
    "dataType": "String",
    "dragLock": false,
    "defaultVisible": false,
    "requiredForUiState": false,
    "defaultWidth": 200,
    "filterable": false,
    "filterType" : "default",
    "headerKey": "isNewProduct",
    "isSortable": false,
    "order": 3,
    "visible": true
  },
  {
    "id": "priceEffectiveDate",
    "title": "Price Effective Date",
    "sortable": false,
    "format": "date",
    "dataType": "String",
    "dragLock": false,
    "editorType": "datebox",
    "editorPropspromo" : { dateFormat :"m/d/Y","minDate":"8/6/2021","maxDate":"8/10/2021"},
    "editorProps" : { dateFormat :"M d, Y","minDate":"8/6/2021","maxDate":"8/10/2021"},
    "defaultVisible": false,
    "requiredForUiState": false,
    "defaultWidth": 200,
    "filterable": false,
    "filterType" : "date",
    "headerKey": "priceEffectiveDate",
    "readOnly": true,
    "isSortable": false,
    "isEditable": true,
    "order": 8,
    "visible": true
  },
  {
    "id": "progress",
    "title": "Progress",
    "sortable": false,
    "format": "progress",
    "defaultWidth": 120,
    "headerKey": "progress",
    "order": 4,
    "visible": true
  },
  {
    "id":"opportunity",
    "title": "Opportunity",
    "sortable": true,
    "format": "percentile",
    "dataType": "number",
    "dragLock": false,
    "defaultVisible": true,
    "requiredForUiState": false,
    "defaultWidth": 160,
    "filterable": false,
    "filterType" : "range",
    "headerKey": "opportunity",
    "isSortable": true,
    "order": 4,
    "visible": true
  },
  {
    "id":"comboDropdownTest",
    "title": "ComboDropDownTest",
    "subTitle": "SubTitle Example",
    "sortable": true,
    "format": "string",
    "dataType": "String",
    "dragLock": false,
    "defaultVisible": true,
    "requiredForUiState": false,
    "defaultWidth": 160,
    "filterable": false,
    "filterType" : "default",
    "headerKey": "approveStatus",
    "isSortable": true,
    "isEditable" : true,
    "editorType" : 'comboDropdownNullable',
    "order": 5,
    "visible": true
  },
  {
    "id": "rowDependentDropdown",
    "title": "RowDependentDropDownTest",
    "sortable": true,
    "format": "string",
    "dataType": "String",
    "dragLock": false,
    "defaultVisible": true,
    "requiredForUiState": false,
    "defaultWidth": 160,
    "filterable": false,
    "filterType" : "default",
    "headerKey": "rowDependentDropdown",
    "isSortable": true,
    "isEditable": true,
    "editorType": 'dropdown',
    "order": 5,
    "visible": true
  },
  {
    "id": "approveStatus",
    "title": "Approval Status",
    "sortable": false,
    "format": "set.tag.approveStatus",
    "dataType": "String",
    "dragLock": false,
    "defaultVisible": false,
    "requiredForUiState": true,
    "defaultWidth": 160,
    "filterable": false,
    "filterType" : "default",
    "headerKey": "approveStatus",
    "isSortable": false,
    "order": 6,
    "visible": true
  },
  {
    "id": "isCompChange",
    "title": "Data Change Trigger",
    "sortable": false,
    "format": "datachange",
    "dataType": "String",
    "dragLock": false,
    "defaultVisible": false,
    "requiredForUiState": false,
    "defaultWidth": 170,
    "filterable": false,
    "filterType" : "default",
    "headerKey": "isCompChange",
    "isSortable": false,
    "order": 7,
    "visible": true
  },
  {
    "id": "productSelected",
    "title": "Active",
    "sortable": false,
    "format": "checkbox",
    "isEditable": true,
    "editorType": "checkbox",
    "dataType": "Boolean",
    "dragLock": false,
    "defaultVisible": true,
    "requiredForUiState": false,
    "defaultWidth": 80,
    "filterable": false,
    "filterType" : "default",
    "headerKey": "productSelected",
    "isSortable": false,
    "order": 9,
    "visible": true
  },
  {
    "id": "productName",
    "title": "Description",
    "sortable": false,
    "format": "string",
    "dataType": "String",
    "dragLock": false,
    "defaultVisible": true,
    "requiredForUiState": false,
    "defaultWidth": 300,
    "filterable": false,
    "filterType" : "default",
    "headerKey": "productName",
    "isSortable": false,
    "order": 10,
    "visible": true
  },
  {
    "id": "size",
    "title": "Size",
    "sortable": false,
    "format": "number",
    "dataType": "String",
    "dragLock": false,
    "defaultVisible": true,
    "requiredForUiState": false,
    "defaultWidth": 90,
    "filterable": false,
    "filterType" : "default",
    "headerKey": "size",
    "isSortable": false,
    "order": 11,
    "visible": true
  },
  {
    "id": "uom",
    "title": "UOM",
    "sortable": false,
    "format": "string",
    "dataType": "String",
    "dragLock": false,
    "defaultVisible": true,
    "requiredForUiState": false,
    "defaultWidth": 90,
    "filterable": false,
    "filterType" : "default",
    "headerKey": "uom",
    "isSortable": false,
    "order": 12,
    "visible": true
  },
  {
    "id": "zone",
    "title": "Zone",
    "sortable": false,
    "format": "string",
    "dataType": "String",
    "dragLock": false,
    "defaultVisible": true,
    "requiredForUiState": false,
    "defaultWidth": 100,
    "filterable": false,
    "filterType" : "default",
    "headerKey": "zone",
    "isSortable": false,
    "order": 13,
    "visible": true
  },
  {
    "id": "currentPrice",
    "title": "Curr Price",
    "sortable": false,
    "format": "currency",
    "dataType": "String",
    "dragLock": false,
    "defaultVisible": true,
    "requiredForUiState": false,
    "defaultWidth": 110,
    "filterable": false,
    "filterType" : "range",
    "headerKey": "currentPrice",
    "isSortable": false,
    "order": 14,
    "visible": true
  },
  { "id": "numbersRoundedTo2Decimals",
    "title": "NumbersRoundedTo2Decimals",
    "sortable": false,
    "format": "number2d",
    "dataType": "number",
    "dragLock": false,
    "defaultVisible": true,
    "requiredForUiState": false,
    "defaultWidth": 150,
    "filterable": false,
    "filterType" : "range",
    "headerKey": "numbersRoundedTo2Decimals",
    "isSortable": false,
    "order": 15,
    "visible": true
  },
  { "id": "numbersCurrencyRoundedTo2Decimals",
    "title": "NumbersCurrencyTo2Decimals",
    "sortable": false,
    "format": "currency",
    "dataType": "number",
    "dragLock": false,
    "defaultVisible": true,
    "requiredForUiState": false,
    "defaultWidth": 150,
    "filterable": false,
    "filterType" : "range",
    "headerKey": "numbersCurrencyRoundedTo2Decimals",
    "isSortable": false,
    "order": 16,
    "visible": true
  },
  { "id": "wholeNumbersOnly",
    "title": "wholeNumbersOnly",
    "sortable": false,
    "format": "number",
    "dataType": "number",
    "editorType":"wholenumber",
    "dragLock": false,
    "defaultVisible": true,
    "requiredForUiState": false,
    "defaultWidth": 150,
    "filterable": false,
    "filterType" : "range",
    "headerKey": "wholeNumber",
    "isSortable": false,
    "order": 17,
    "visible": true
  },
  {
    "id": "lastApprovedPrice",
    "title": "Last Approved Price",
    "sortable": false,
    "format": "currency",
    "dataType": "String",
    "dragLock": false,
    "defaultVisible": true,
    "requiredForUiState": false,
    "defaultWidth": 150,
    "filterable": false,
    "filterType" : "range",
    "headerKey": "lastApprovedPrice",
    "isSortable": false,
    "order": 18,
    "visible": true
  },
  {
    "id": "dropdownTest",
    "title": "DropDown Test",
    "sortable": false,
    "format": "string",
    "dataType": "String",
    "dragLock": false,
    "defaultVisible": true,
    "requiredForUiState": false,
    "defaultWidth": 150,
    "filterable": false,
    "headerKey": "dropdownTest",
    "isSortable": false,
    "editorType" : "dropdown",
    "filterType" : "default",
    "isEditable" : true,
    "order": 19,
    "visible": true
  },
  {
    "id": "newPrice",
    "title": "Recom Price",
    "sortable": false,
    "format": "currency",
    "dataType": "String",
    "dragLock": false,
    "defaultVisible": true,
    "requiredForUiState": false,
    "defaultWidth": 110,
    "filterable": false,
    "filterType" : "range",
    "headerKey": "newPrice",
    "isSortable": false,
    "order": 20,
    "visible": true
  },
  {
    "id": "currentGM",
    "title": "Curr GM Chg $",
    "titleSymbol":"CR",
    "titleSymbolTooltip" : "Current to Recommended",
    "sortable": false,
    "format": "currencyround",
    "dataType": "String",
    "dragLock": false,
    "defaultVisible": true,
    "requiredForUiState": false,
    "defaultWidth": 110,
    "filterable": false,
    "filterType" : "range",
    "headerKey": "currentGM",
    "isSortable": false,
    "order": 21,
    "visible": true
  },
  {
    "id": "currentGMPct",
    "title": "Curr GM %",
    "sortable": false,
    "format": "percent",
    "dataType": "String",
    "dragLock": false,
    "defaultVisible": true,
    "requiredForUiState": false,
    "defaultWidth": 110,
    "filterable": false,
    "filterType" : "range",
    "headerKey": "currentGMPct",
    "isSortable": false,
    "order": 22,
    "visible": true
  },
  {
    "id": "priceApprdDiff",
    "title": "Price Chg $",
    "titleSymbol":"AR",
    "titleSymbolTooltip": "Approved to Recommended",
    "sortable": false,
    "format": "currency",
    "dataType": "String",
    "dragLock": false,
    "defaultVisible": true,
    "requiredForUiState": false,
    "defaultWidth": 150,
    "filterable": false,
    "filterType" : "range",
    "headerKey": "priceApprdDiff",
    "isSortable": false,
    "order": 23,
    "visible": true
  },
]



/* set up for interactive grids where numeric values are numbers and not formatted strings from GridBuilder */
const myconfigAsNumericsFn = () => {
  return ( myconfig.map(header =>
      ({
        ...header,
        "dataType": ((header.dataType === 'String') && (["currency","currencyround", "currency3d", "percent","percentround","number","numberround","number2d","number3d"].includes(header.format)) && "number")
      })
    )
  )
};

const myconfigAsNumerics = myconfigAsNumericsFn();

const stringToNumber = (stringValue,a,b) => {
  let negative = 1;
  if (typeof stringValue !== "string") return stringValue;
  if (stringValue.indexOf(')') > 1) negative=-1;
  return stringValue.replace(/[^\d^\.]/gi,'') * negative;
}


const mydataAsNumericsFn = () => {
  return ({
    rows: mydata.rows.map(row =>
      ({
          ...row,
          ...Object.assign({},{},...(myconfigAsNumerics.filter(header => header.dataType === "number").map(header =>
            ({ [header.id]: stringToNumber(row[header.id],row,header.id)})
          )))
        }
      )),
    total: 8
  })
};

const mydataAsNumerics = mydataAsNumericsFn();

const myRowDependentMenusFn = () => {
  return ({
    "rowDependentDropdown": {
      menusByRow: Object.assign(...mydata.rows.map(row => (
        { [row.id]:
          {
            items: [
              {label: "hi" + row.id, value: "hi" + row.id},
              {label: "hello" + row.id, value: "hello" + row.id}
            ]
          }
        }
      )
      )
      )
    }
  });
}

const myRowDependentMenus = myRowDependentMenusFn();

export {mydata, myconfig, mydataAsNumerics, myconfigAsNumerics, myRowDependentMenus, infiniteScrollData};
